micronaut:
  security:
    oauth2:
      clients:
        cognito:
          client-id: ${OAUTH_CLIENT_ID:77por3ndcbviqde5o7brav5poj}
          client-secret: ${OAUTH_CLIENT_SECRET:}
          openid:
            issuer: https://cognito-idp.${COGNITO_REGION:us-east-1}.amazonaws.com/${COGNITO_POOL_ID:us-east-1_lUZuZs1zq}/

datasources:
  default:
    url: jdbc:postgresql://localhost:5438/demodb # Use JDBC style url
    password: ${pg.secret:}
